export const FETCH_ARTICLE_SUCCESS = '@content/FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLES_SUCCESS = '@content/FETCH_ARTICLES_SUCCESS';
export const FETCH_ERROR = '@content/FETCH_ERROR';
export const FETCH_PUBLICATIONS_SUCCESS = '@content/FETCH_PUBLICATIONS_SUCCESS';
export const FETCH_START = '@content/FETCH_START';
