export const TOGGLE_VOCALIZATION = '@ajar/SETTINGS/TOGGLE_VOCALIZATION'
export const TOGGLE_TRANSCRIPTION = '@ajar/SETTINGS/TOGGLE_TRANSCRIPTION'
export const SET_ROMANIZATION = '@ajar/SETTINGS/SET_ROMANIZATION'
