export const CLOSE_SETTINGS = 'CLOSE_SETTINGS';
export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const SET_ROMANIZATION_STANDARD = 'SET_ROMANIZATION_STANDARD';
export const SET_VOICE_NAME = 'SET_VOICE_NAME';
export const TOGGLE_TRANSCRIPTION = 'TOGGLE_TRANSCRIPTION';
export const TOGGLE_VOCALIZATION = 'TOGGLE_VOCALIZATION';
